In [1]:
import numpy as np
from pdb import set_trace

In [13]:
#inp = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1],[1,1,1],[1,1,1]])
inp = np.array([[0,0,1],[0,1,1]])
y = np.array([[0,1]]).T


theta1 = 2*np.random.random((3,2)) - 1

theta2 = 2*np.random.random((2,1)) - 1

for j in range(60000):
    #set_trace()
    #ForwardPass
    z2 = np.dot(inp,theta1)     #Theta*input
    a2 = 1/(1+np.exp(-(z2)))    #sig(z2)
    z3 = np.dot(a2,theta2)      #theta2*a2
    a3 = 1/(1+np.exp(-(z3)))    #sig(z3)

    #BackProp
    dJda3 = (y - a3)            #dJ/da3
    da3dz3 = (a3*(1-a3))        #da3/dz3
    dz3dtheta2 = a2

    #Update
    theta2 += a2.T.dot(dJda3 * da3dz3)
    theta1 += inp.T.dot((dJda3 * da3dz3).dot(theta2.T) * (a2 * (1-a2)))
print("Input")
print(inp)
print("Theta1")
print(theta1)
print("Z2")
print(z2)
print("A2")
print(a2)
print("Theta2")
print(theta2)
print("Z3")
print(z3)
print("A3")
print(z3)


Input
[[0 0 1]
 [0 1 1]]
Theta1
[[-0.33235023 -0.17669354]
 [-5.24043315  4.58119908]
 [ 2.29773029 -1.94080109]]
Z2
[[ 2.2977284  -1.9407988 ]
 [-2.94270123  2.64039617]]
A2
[[0.90868873 0.12556013]
 [0.05008261 0.93341659]]
Theta2
[[-7.29796724]
 [ 6.54730721]]
Z3
[[-5.80949402]
 [ 5.74585655]]
A3
[[-5.80949402]
 [ 5.74585655]]


# 11 Lines
X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])

y = np.array([[0,1,1,0]]).T

syn0 = 2*np.random.random((3,4)) - 1

syn1 = 2*np.random.random((4,1)) - 1

for j in range(0,60000):

    l1 = 1/(1+np.exp(-(np.dot(X,syn0))))
    
    l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
    
    l2_delta = (y - l2)*(l2*(1-l2))
    
    l1_delta = l2_delta.dot(syn1.T) * (l1 * (1-l1))
    
    syn1 += l1.T.dot(l2_delta)
    
    syn0 += X.T.dot(l1_delta)
    