In [32]:
import numpy as np
import pandas as pd
from statistics import mode
import difflib
from sklearn import metrics
import math

In [33]:
df = pd.DataFrame(pd.read_csv("cancerdata.csv"))
df['diagnosis'] = df['diagnosis'].replace(['B'], 0)
df['diagnosis'] = df['diagnosis'].replace(['M'], 1)
df['diagnosis'] = pd.to_numeric(df['diagnosis'])
train = df.sample(frac=0.8, random_state=25)
test = df.drop(train.index)
train.shape

(455, 33)

In [34]:
def normalize(X,base):
    result = np.zeros(X.shape)
    for (index, colname) in enumerate(base):
        if(index > 1 and index < 32):
            result[:,index-2] = (base[colname].values-base[colname].values.min())/(base[colname].values.max()-base[colname].values.min())
    return result

In [55]:
X = np.zeros((455,30))
X_test = np.zeros((114,30))
X = normalize(X,train)
X_test = normalize(X_test,test)
X.shape

(455, 30)

In [36]:
print(X.shape)
print(X_test.shape)
X_test

(455, 30)
(114, 30)


array([[0.25883856, 0.21043324, 0.26798424, ..., 0.63702891, 0.56640814,
        0.74076058],
       [0.31941881, 0.51591512, 0.34420565, ..., 0.8079034 , 0.47212797,
        0.94108195],
       [0.43300677, 0.4305924 , 0.44440605, ..., 0.75850714, 0.49878817,
        0.63149438],
       ...,
       [0.389938  , 0.87002653, 0.4119273 , ..., 0.86205635, 0.59161415,
        0.91751473],
       [0.45525108, 0.75773652, 0.44578813, ..., 0.51884376, 0.13814833,
        0.24584896],
       [0.64456434, 0.81299735, 0.66553797, ..., 0.96963044, 0.59112942,
        0.73647563]])

In [44]:
Y_answ = test.diagnosis.values
Y_pred = np.zeros(Y_answ.shape)
Distancia = np.zeros((114,455))
Y_train = train.diagnosis.values
Soma = 0
k = 3
Y_train.shape

(455,)

In [49]:
f = open('out.txt', 'w')
for (index, colname) in enumerate(X_test):#114
    for (index2, colname2) in enumerate(X):#455
        Distancia[index,index2] = math.sqrt(((X_test[index,:]-X[index2,:])**2).sum())  #raiz da soma dos quadrados
    #f.write('\n\nAntes\n\n')
    #f.write(str(Distancia[:,index]))
    #f.write('\n\nklni\n\n')
    klni = Distancia[index,:].argsort()[:k]         # K lowest numbers indexes
    labels, freq = np.unique(Y_train[klni], return_counts = True)
    Y_pred[index] = labels[np.argmax(freq)]
Y_pred = Y_pred.astype(int)
Y_pred

array([1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1])

In [51]:
klni

array([188, 440, 408], dtype=int64)

In [52]:
labels, freq = np.unique(Y_train[klni], return_counts = True)
print(labels,freq)
print(Y_train[klni])
print(Distancia[:,klni])
np.unique([1,1,2,3,3,4],return_counts = True)

[1] [3]
[1 1 1]
[[1.35425865 1.77212121 1.87195228]
 [1.13065725 1.61969583 1.69222819]
 [0.87804933 1.39198739 1.34544801]
 [1.72135262 2.24261824 2.12316085]
 [1.06087178 1.31408072 1.62581682]
 [1.43804134 1.69230647 1.41064907]
 [1.31572745 1.72338349 1.50103712]
 [1.42561639 2.06485996 1.87024748]
 [2.36135289 2.82755134 2.70457104]
 [2.12294711 2.62916195 2.42968304]
 [2.10269579 2.54726368 2.42576699]
 [1.07017593 1.66495474 1.57131824]
 [1.0574975  1.37865855 1.40921425]
 [1.32734272 1.83553545 1.727955  ]
 [2.18548687 2.64633103 2.41728953]
 [2.39925436 2.68257958 2.67763466]
 [2.03235571 2.30515793 2.30550257]
 [1.83212871 2.33913158 2.14458652]
 [2.02188603 2.45692142 2.30430451]
 [1.6751985  2.2035303  2.02353242]
 [1.4399903  1.92288368 1.71528563]
 [2.54963683 2.96437471 2.91268305]
 [1.77318691 2.2066472  2.08889017]
 [1.95800567 2.46693451 2.25203281]
 [2.21654926 2.58663041 2.48725933]
 [1.39986015 1.74710062 1.67645113]
 [1.8783413  2.33650662 2.26009534]
 [1.27841583

(array([1, 2, 3, 4]), array([2, 1, 2, 1], dtype=int64))

In [53]:
Y_answ

array([1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 1], dtype=int64)

In [54]:
negado = np.logical_not(Y_pred)
print("Accuracy:", metrics.accuracy_score(Y_answ, Y_pred))
print("Inaccuracy:", metrics.accuracy_score(Y_answ, negado))
negado

Accuracy: 0.9473684210526315
Inaccuracy: 0.05263157894736842


array([False, False, False,  True, False, False, False, False,  True,
        True,  True, False, False, False,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
       False, False,  True,  True,  True, False,  True,  True,  True,
       False, False,  True,  True, False, False,  True,  True,  True,
       False, False,  True, False, False,  True,  True,  True, False,
        True,  True,  True, False,  True, False, False,  True, False,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True, False,  True, False,  True, False,  True, False,  True,
        True,  True,  True,  True, False,  True,  True, False,  True,
        True,  True, False, False,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True, False,  True, False,  True,
       False, False,  True, False, False, False])