In [19]:
import numpy as np

In [58]:
rs = np.random.RandomState(42)
x = rs.rand(10,3)
x = np.vstack(([1]*x.shape[0],x.T)).T
W1 = rs.rand(4,4)
W2 = rs.rand(5)
x

array([[1.        , 0.37454012, 0.95071431, 0.73199394],
       [1.        , 0.59865848, 0.15601864, 0.15599452],
       [1.        , 0.05808361, 0.86617615, 0.60111501],
       [1.        , 0.70807258, 0.02058449, 0.96990985],
       [1.        , 0.83244264, 0.21233911, 0.18182497],
       [1.        , 0.18340451, 0.30424224, 0.52475643],
       [1.        , 0.43194502, 0.29122914, 0.61185289],
       [1.        , 0.13949386, 0.29214465, 0.36636184],
       [1.        , 0.45606998, 0.78517596, 0.19967378],
       [1.        , 0.51423444, 0.59241457, 0.04645041]])

In [38]:
def g(a):
    return 1/(1+np.exp(-a))

In [64]:
a = g(np.dot(x,W1))
a = np.vstack(([1]*a.shape[0],a.T)).T
a

array([[1.        , 0.83819992, 0.82597674, 0.61883128, 0.87448411],
       [1.        , 0.78545543, 0.70370404, 0.5761088 , 0.76637681],
       [1.        , 0.78193357, 0.75865771, 0.58516374, 0.85590927],
       [1.        , 0.79227949, 0.83670966, 0.63047278, 0.8416857 ],
       [1.        , 0.82677199, 0.75068469, 0.5966657 , 0.77830234],
       [1.        , 0.73318926, 0.71704943, 0.57293714, 0.81231385],
       [1.        , 0.77642517, 0.76928226, 0.59640411, 0.82355929],
       [1.        , 0.72206708, 0.67809242, 0.55922153, 0.79411268],
       [1.        , 0.83090439, 0.74390683, 0.58697397, 0.81973013],
       [1.        , 0.81921722, 0.70872938, 0.57591157, 0.78971965]])

In [65]:
g(np.dot(a , W2))

array([0.89673687, 0.87593508, 0.88807054, 0.8922391 , 0.88257273,
       0.878527  , 0.88542498, 0.87339205, 0.88633524, 0.88052269])

In [67]:
a = g(np.dot(x,W1))
a
np.dot(a, W2)

ValueError: shapes (10,4) and (5,) not aligned: 4 (dim 1) != 5 (dim 0)